//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PbiMonitor_Web.SQL_Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PbiMonitorEntities : DbContext
    {
        public PbiMonitorEntities()
            : base("name=PbiMonitorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<report> reports { get; set; }
        public virtual DbSet<t_Security_Log> t_Security_Log { get; set; }
        public virtual DbSet<t_Security_Users> t_Security_Users { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<user_permissions> user_permissions { get; set; }
        public virtual DbSet<schedulehistory> schedulehistories { get; set; }
        public virtual DbSet<UserActivity> UserActivities { get; set; }
        public virtual DbSet<workspace> workspaces { get; set; }
        public virtual DbSet<dataset> datasets { get; set; }
        public virtual DbSet<dashboard> dashboards { get; set; }
        public virtual DbSet<AdUser> AdUsers { get; set; }
        public virtual DbSet<vw_WS_DS_REP> vw_WS_DS_REP { get; set; }
    
        public virtual int TruncateAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TruncateAll");
        }
    }
}
