//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PbiMonitor_Web.SQL_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserActivity
    {
        public int PK { get; set; }
        public string RequestURL { get; set; }
        public string JsonInfo { get; set; }
        public string CallerPrincipalName { get; set; }
        public Nullable<System.DateTime> LastTimeUpdated { get; set; }
        public string StartDate { get; set; }
    }
}
