//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PbiMonitor_Web.SQL_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_permissions
    {
        public string DisplayName { get; set; }
        public string UserPrincipalName { get; set; }
        public string UserType { get; set; }
        public string workspaceid { get; set; }
        public string workspacetype { get; set; }
        public string CallerPrincipalName { get; set; }
        public Nullable<System.DateTime> LastTimeUpdated { get; set; }
    }
}
