//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PbiMonitor_Web.SQL_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_WS_DS_REP
    {
        public string workspaceName { get; set; }
        public string workspaces_id { get; set; }
        public string WorkspaceType { get; set; }
        public string isReadOnly { get; set; }
        public string IsOnDedicatedCapacity { get; set; }
        public Nullable<int> numbOfDatasets { get; set; }
        public Nullable<int> numbOfReports { get; set; }
        public Nullable<int> numbOfUsers { get; set; }
        public string WorkspaceState { get; set; }
        public Nullable<int> MasterAccountAccess { get; set; }
        public string workspaces_user { get; set; }
        public string UserType { get; set; }
        public string datasets_name { get; set; }
        public string datasets_id { get; set; }
        public string datasets_configuredBy { get; set; }
        public string addRowsAPIEnabled { get; set; }
        public string isRefreshable { get; set; }
        public string dataset_type { get; set; }
        public string reports_name { get; set; }
        public string reports_id { get; set; }
        public string reportType { get; set; }
    }
}
