//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PbiMonitor_Web.SQL_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class workspace
    {
        public string id { get; set; }
        public string name { get; set; }
        public string isReadOnly { get; set; }
        public string IsOnDedicatedCapacity { get; set; }
        public string CapacityId { get; set; }
        public string Description { get; set; }
        public string type { get; set; }
        public string state { get; set; }
        public string IsOrphaned { get; set; }
        public Nullable<int> Accessible { get; set; }
        public Nullable<int> MasterAccountAccess { get; set; }
        public string CallerPrincipalName { get; set; }
        public Nullable<System.DateTime> LastTimeUpdated { get; set; }
    }
}
